[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[[redirects]]
  from = "/app-ads.txt"
  to = "https://your-domain.com/ads"
  status = 301

[[plugins]]
  package = "@netlify/plugin-nextjs"
