[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[redirects]]
  from = "/app-ads.txt"
  to = "https://daplay.eu/app-ads.txt"
  status = 301

[[plugins]]
  package = "@netlify/plugin-nextjs"
