[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[[redirects]]
  from = "/app-ads.txt"
  to = "/app-ads.txt"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
